---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: apache-camel
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/kshitij-tripathi/apache-camel-with-flux.git
