---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apche-camel-root
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./
  prune: true
  retryInterval: 5m0s
  sourceRef:
    kind: GitRepository
    name: apache-camel
  timeout: 4m0s
  wait: true
