---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apache-camel-k
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: apache-camel
